017/solution
ga-wdi-boston/css_layout_with_bootstrap pull request #33
Opened 2017-03-29 22:08 UTC by Jcornmanhomonoff

Update solution.

2017-03-30 21:38 UTC, jrhorn424 commented on assets/scripts/index.js
> +    const input = $('#name').val()
We should be using `getFormFields` as much as possible in my opinion.

2017-03-30 21:39 UTC, jrhorn424 requested changes
I believe we shouldn't be using jQuery to select form inputs, instead depend on `getFormFields`.

2017-04-03 16:11 UTC, Jcornmanhomonoff commented
I did not make these changes for lm01 as I ran out of time. I can address them for 017 if you like. I made a few small changes that rearrange the HTML so that it follows the README instructions more closely.

2017-04-04 00:46 UTC, jrhorn424 commented
@Jcornmanhomonoff I'll go ahead and update the solution and close this. If you'd like to address my comments for 017 delivery, that's great. I'll open an issue and assign you. If you don't get to it this time, no big deal.

2017-04-04 00:46 UTC, jrhorn424 approved these changes

2017-04-04 00:51 UTC, jrhorn424 commented
@Jcornmanhomonoff Please target `solution` instead of `master` next time. Thanks!

2017-04-04 00:51 UTC, closed without merging